version: "3.7"

services:

  localstack:
    image: localstack/localstack-full:0.12.3
    container_name: localstack
    ports:
      - 4566-4593:4566-4593
      - 8082:8080
    environment:
      - SERVICES=s3,ses
      - PORT_WEB_UI=8080
      - DEBUG=0
      - DATA_DIR=./tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/hadoop:/usr/src/app
      - ./it/aws/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/localstack-entrypoint.sh